---
title: "Packages and Data"
output: pdf_document
---

# Install packages

```{r setup}
install.packages(c("dplyr", "tidyverse", "rmarkdown", "knitr", "gapminder", "tidytext", "devtools", "usethis"))

install.packages("haven")

library(dplyr)
library(tidyverse)
library(haven)
```

# Read data file into dataset

```{r file}
anes2016all <- read_dta("anes2016.dta")
```

# Select important variables

* columns with alphanumeric codes are from original data set
* columns with phrase codes are from pre-coded data set
* use Congressional district to determine urban/suburban/rural status

```{r}
anes2016var <- anes2016all %>%
  select(c(
           V160001, # 2016 case ID
           V161010d, # Pre: vote section - FIPS state code for address
           V161010e, # Pre: vote section- 2-char state postal abbreviation for sample address
           V161010f, # Pre: vote section- U.S. House District (115th Congress) for sample address
           V161095, # Pre: FT Democratic party
           V161096, # Pre: FT Republican party
           V161126, # Pre: 7pt scale liberal conservative self placement
           V161127, # Pre: if R had to choose liberal or conservative self
           V161155, # Pre: Party ID Does R think of self as Dem, Rep, Ind or what
           V161155a, # Pre: Party ID other specifys
           V161156, # Pre: Party ID strong - Dem or Rep
           V161157, # Pre: No party ID - closer to Dem or Reps
           V161158x, # PreL Summary Party ID
           V161178, # Pre: 7pt scale spending and services self-placement
           V161184, # Pre: 7pt scale govt-private medical self-placement
           V161187, # Pre: should fed govt make it more difficult to buy a gun
           V161189, # Pre: 7pt scale guaranteed job-income self-placement
           V161192, # Pre: U.S. govt policy toward undocumented immigrants
           V161193, # Pre: favor or oppose ending birthright citizenship
           V161193a, # Pre: strength R favors or opposes end birthright citizenship
           V161194x, # Pre: SUMMARY - BIRTHRIGHT CITIZENSHIP
           V161195, # PRE: CHILDREN BROUGHT ILLEGALLY SENT BACK
           V161195x, # PRE: SUMMARY - CHILDREN BROUGHT ILLEGALLY SENT BACK
           V161196x, # SUMMARY: BUILD WALL WITH MEXICO
           V161198, # PRE: 7PT SCALE GOVT ASSISTANCE TO BLACKS SELF-PLACEMENT
           V161201, # PRE: 7PT SCALE ENVIRONMENT-JOBS TRADEOFF SELF-PLACEMENT
           V161204, # PRE: DOES R FAVOR OR OPPOSE AFFIRMATIVE ACTION IN UNIVERSITIES
           V161204x, # PRE: SUMMARY - FAVOR OR OPPOSE AFFIRMATIVE ACTION IN UNIVERSITIES
           V161205, # PRE: FEDERAL BUDGET SPENDING (FBS): SOCIAL SECURITY
           V161206, # PRE: FBS: PUBLIC SCHOOLS
           V161207, # PRE: FBS: SCIENCE AND TECHNOLOGY
           V161208, # PRE: FBS: DEALING WITH CRIME
           V161209, # PRE: FBS: WELFARE PROGRAMS
           V161210, # PRE: FBS: CHILD CARE
           V161211, # PRE: FBS: AID TO THE POOR
           V161212, # PRE: FBS: PROTECTING THE ENVIRONMENT
           V161224, # PRE: GOVT ACTION ABOUT RISING TEMPERATURES
           V161225x, # PRE: SUMMARY - GOVT ACTION ABOUT RISING TEMPERATURES
           V161226, # PRE: REQUIRE EMPLOYERS TO OFFER PAID LEAVE TO PARENTS OF NEW CHILDREN
           V161226x, # PRE: SUMMARY - REQUIRE EMPLOYERS TO OFFER PAID LEAVE TO NEW PARENTS
           V161227, # PRE: SERVICES TO SAME SEX COUPLES
           V161227x, # PRE: SUMMARY - SERVICES TO SAME SEX COUPLES
           V161228, # PRE: TRANSGENDER BATHROOM POLICY
           V161228x, # PRE: SUMMARY - TRANSGENDER BATHROOM POLICY
           V161229, # PRE: SHOULD LAWS PROTECT GAYS AND LESBIANS AGAINST JOB DESCRIMINATION
           V161229x, # PRE: SUMMARY - LAWS TO PROTECT GAYS AND LESBIANS AGAINST JOB DISCRIMINATION
           V161230, # PRE: SHOULD GAY AND LESBIAN COUPLES BE ALLOWED TO ADOPT
           V161231, # PRE: R POSITION ON GAY MARRIAGE
           V161232, # PRE: STD ABORTION: SELF-PLACEMENT
           V161233, # PRE: R FAVOR OR OPPOSE DEATH PENALTY
           V161233x, # PRE: SUMMARY - FAVOR OR OPPOSE DEATH PENALTY
           V161267, # PRE: RESPONDENT AGE
           V161267x, # PRE: SUMMARY - RESPONDENT AGE GROUP
           V161270, # PRE: HIGHEST LEVEL OF EDUCATION
           V161304, # PRE: THINK OF SELF AS BELONGING TO SOCIAL CLASS
           V161308x, # PRE: SUMMARY - R SELF-IDENTIFIED SOCIAL CLASS
           V161310x, # PRE: SUMMARY - R SELF-IDENTIFIED RACE
           V161331x, # PRE: SUMMARY - LENGTH IN CURRENT COMMUNITY
           V161333, # PRE: CITY/STATE OF PREVIOUS RESIDENCE
           V161507, # PRE FTF CASI/WEB: INNOCENT REMARKS AS SEXIST
           V161508, # PRE FTF CASI/WEB: WOMEN FAIL TO APPRECIATE WHAT MEN DO TO THEM
           V161509, # PRE FTF CASI/WEB: WOMEN SEEK TO GAIN POWER BY GETTING CONTROL OVER MEN
           V161510, # PRE FTF CASI/WEB: WOMEN PUT MEN ON A TIGHT LEASH
           V161511, # PRE FTF CASI/WEB: SEXUAL ORIENTATION OF R
           V161512, # PRE FTF CASI/WEB: SEXUAL ORIENTATION OF FAMILY AND FRIENDS
           V162024a, # POST: STATE INCLUDED IN ADDRESS OF REGISTRATION (NOT REGISTERED AT SAMP AD)
           V162024b, # POST: CITY INCLUDED IN ADDRESS OF REGISTRATION (NOT REGISTERED AT SAMP AD)
           V162025, # POST: STATE OF REGISTRATION
           V162026a, # POST: STATE OF REGIST FOR POST VOTE SECTION
           V162026b, # POST: STATE OF REGIST FOR POST VOTE SECTION SAME AS SAMPLE ADDRESS STATE
           V162030, # POST: PARTY OF REGISTRATION
           V162030x, # PRE-POST: SUMMARY - PARTY OF REGISTRATION
           V162040, # POST: FOR WHOM DID R VOTE FOR U.S. HOUSE (BALLOT CARD), 
           # V162O41, # POST: FOR WHOM DID R VOTE FOR U.S. HOUSE (NO BALLOT CARD)
           V162128, # POST: THINK OF SELF AS BELONGING TO CLASS
           V162132, # POST: R SOCIAL CLASS
           V162133, # POST: IS R UPPER MIDDLE, MIDDLE, LOWER MIDDLE CLASS
           V162146, # POST: DOES R FAVOR OR OPPOSE VACCINES IN SCHOOLS
           V162147x, # POST: SUMMARY - FAVOR/OPPOSE VACCINES IN SCHOOLS
           V162148, # POST: DOES R FAVOR OR OPPOSE GOVT REDUCING INCOME INEQUALITY
           V162150x, # POST: SUMMARY - FAVOR/OPPOSE EQUAL PAY FOR MEN AND WOMEN
           V162157, # POST: WHAT SHOULD IMMIGRATION LEVELS BE
           V162158, # POST: HOW LIKELY IMMIGRATION WILL TAKE AWAY JOBS
           V162161, # POSTL HEALTH BENEFITS OF VACCINATION OUTWEIGH RISKS
           V162162x, # POST: SUMMARY - BENEFITS/RISKS OF VACCINATIONS
           V162171, # POST: 7PT SCALE LIBERAL-CONSERVATIVE: SELF PLACEMENT
           V162171a, # POST: IF I HAD TO CHOOSE, LIBERAL OR CONSERVATIVE
           V162178, # POST: HAS INCREASE IN GOVT WIRETAP POWERS GONE TOO FAR
           V162179, # POST: SHOULD MARIJUANA BE LEGAL
           V162180, # POST: SHOULD GOV DO MORE OR LESS TO REGULATE BANKS
           V162180x, # POST: SUMMARY - GOV SHOULD DO MORE/LESS TO REGULATE BANKS
           V162183, # POST: GOVT BIGGER BECAUSE TOO INVOLVED OR BIGGER PROBLEMS
           V162184, # POST: NEED STRONGER GOVT FOR COMPLEX PROBLEMS OR FREE MARKET
           V162185, # POST: LESS GOVT BETTER OR MORE THAT GOVT SHOULD BE DOING
           V162186, # POST: REGULATION OF BUSINESS
           V162191, # POST: IS ONE OF THE PARTIES MORE CONSERVATIVE THAN THE OTHER
           V162191a, # POST: WHICH IS THE PARTY THAT IS MORE CONSERVATIVE
           V162192, # POST: SHOULD THE MINIMUM WAGE BE RAISED
           V162193, # POST: INCREASE OR DECREASE GOV SPENDING TO HELP PEOPLE PAY FOR HEALTH CARE
           V162193x, # POST: SUMMARY - INCREASE/DECREASE GOV SPENDING FOR HEALTH CARE
           V162207, # POST: AGREE/DISAGREE: WORLD IS CHANGING AND WE SHOULD ADJUST
           V162208, # POST: AGREE/DISAGREE: NEWER LIFESTYLES BREAKING DOWN SOCIETY
           V162209, # POST: AGREE/DISAGREE: BE MORE TOLERANT OF OTHER MORAL STDS
           V162210, # POST: AGREE/DISAGREE: MORE EMPHASIS ON TRANDITIONAL FAMILY VALUES
           V162211, # POST: AGREE/DISAGREE: BLACKS SHD WORK WAY UP W/O SPECIAL FAVORS
           V162212, # POST: AGREE/DISAGREE: PAST SLAVERY MAKE MORE DIFF FOR BLACKS
           V162213, # POST: AGREE/DISAGREE: BLACKS HAVE GOTTEN LESS THAN DESERVE
           V162214, # POST: AGREE/DISAGREE: BLACKS MUST TRY HARDER TO GET AHEAD
           V162230x, # POST: SUMMARY - BETTER IF MAN WORKS AND WOMAN TAKES CARE OF HOME
           V162238x, # POST: SUMMARY - FAVOR PREFERENTIAL HIRING AND PROMOTION OF BLACKS
           V162239, # POST: CHILD TRAIT MORE IMPORTANT: INDEPENDENCE OR RESPECT
           V162240, # POST: CHILD TRAIT MORE IMPORTANT: CURIOSITY OR GOOD MANNERS
           V162241, # POST: CHILD TRAIT MORE IMPORTANT: OBEDIENCE OR SELF-RELIANCE
           V162242, # POST: CHILD TRAIT MORE IMPORTANT: CONSIDERATE OR WELL-BEHAVED
           V162243, # POST: SOCIETY SHOULD MAKE SURE EVERYONE HAS EQUAL OPPORTUNITY
           V162244, # POST: WE'D BE BETTER OFF IF WORRIED LESS ABOUT EQUALITY
           V162245, # POST: NOT A BIG PROBLEM IF SOME HAVE MORE CHANCES IN LIFE
           V162246, # POST: IF PEOPLE WERE TREATED MORE FAIRLY WOULD BE FEWER PROBS
           V162256, # POST: R'S INTEREST IN POLITICS
           V162257, # POST: R FOLLOWS POLITICS IN MEDIA
           V162258, # POST: R UNDERSTANDS MOST IMPORTANT POLITICAL ISSUES
           V162268, # POST: IMMIGRANTS ARE GENERALLY GOOD FOR AMERICA'S ECONOMY
           V162269, # POST: AMERICA'S CULTURE IS GENERALLY HARMED BY IMMIGRANTS
           V162276, # POST: GOV SHOULD TAKE MEASURES TO REDUCE DIFFERENCE IN INCOME LEVELS
           V168112, # FTF ONLY: POST IWR OBS - R LEVEL OF INFORMATION
  ))

anes2016recode <- anes2016all %>%
  select(c(
           caseid, # CASE IDENTIFICATION NUMBER
           polinterest1, # 2 = R VERY MUCH INTERESTED IN POLITICS ... 0 = R NOT MUCH INTERESTED
           stfips, # STATE FIPS CODE
           stabbrev, # STATE ABBREVIATION
           congdist, # CONGRESSIONAL DISTRICT NUMBER
           libconpre, # POLITICAL ID (WITH MISSING): 6 = STRONG CONSERVATIVE ... 0 = STRONG LIBERAL
           flibcon, # FORCED ID FOR MISSING: 2 = CONSERVATIVE; 1 = MODERATE; 0 = LIBERAL
           libcon, # POLITICAL ID (FORCED): 6 = STRONG CONSERVATIVE ... 0 = STRONG LIBERAL
           partyid, # PARTISAN ID: 6 = STRONG REP ... 0 = STRONG DEM
           govservice, # GOV SERVICES SCALE: 6 = GOV SHOULD PROVIDE MORE SERVICES
           medinsur, # MEDICAL INSURANCE SCALE: 6 = GOV INSUANCE ... 0 = PRIVATE INSURANCE
           fedgun, # 2 = GUN PURCHASE EASIER, 1 = THE SAME, 0 = GUN PURCHASE MORE DIFFICULT
           govjob, # GOV JOB SCALE: 6 = GOV GUARANTEES JOBS ... 0 = GET JOBS ON OWN
           immpolicy, # 3 = REMAIN NO PENALTY, 2 = REMAIN PENALTY, 1 = GUEST WORKER, 0 = DEPORT
           immnopenalty, # 1 = REMAIN IN US WITHOUT PENALTY, 0 = OTHERWISE
           immpenalty, # 1 = REMAIN IN US BUT WITH PENALTY, 0 = OTHERWISE
           immguest, # 1 = REMAIN IN US GUEST WORKER PROGRAM, 0 = OTHERWISE
           immdeport, # 1 = ILLEGAL IMMIGRANTS CLASSIFIED AS FELONS AND DEPORTED, 0 = OTHERWISE
           immbirth, # 6 = R SUPPORTS BIRTHRIGHT CITIZENSHIP ... 0 = R SUPPORTS BIRTHPLACE CITIZENS
           immcitizen, # 5 = R SUPPORTS SENDING IMMIGRANT CHILDREN BACK ... 0 = ALLOWED TO STAY
           immmexwall, # 6 = R SUPPORTS BORDER WALL WITH MEXICO ... 0 = OPPOSES BORDER WALL
           govblacks, # AID TO BLACKS SCALE: 6 = GOV SHOULD HELP BLACKS ... 0 = BLACKS HELP SELVES
           envjobs, # ENVIRONMENT-JOBS TRADEOFF: 6 = PROTECT ENVIORNMENT ... 0 = PROTECT JOBS
           aacolleges, # 6 = R SUPPORTS AFFIRMATIVE ACTION IN COLLEGES ... 0 = R OPPOSES
           ssocsec, # 1 = INCREASED SPENDING ON SOCSEC, 0 = KEEP SAME, -1 = DECREASED SPENDING
           sschools, # 1 = INCREASED SPENDING ON SCHOOLS, 0 = KEEP SAME, -1 = DECREASED SPENDING
           sscience, # 1 = INCREASED SPENDING ON SCIENCE, 0 = KEEP SAME, -1 DECREASED SPENDING
           scrime, # 1 = INCREASED SPENDING ON CRIME, 0 = KEEP SAME, -1 = DECREASED SPENDING
           swelfare, # 1 = INCREASED SPENDING ON WELFARE, 0 = KEEP SAME, -1 = DECREASED SPENDING
           schildcare, # 1 = INCREASED SPEND ON CHILD CARE, 0 = KEEP SAME, -1 = DECREASED SPENDING
           spoor, # 1 = INCREASED SPEND ON POOR, 0 = KEEP SAME, -1 = DECREASED SPENDING
           senviron, # 1 = INCREASED SPEND ON ENVIRONMENT, 0 = KEEP SAME, -1 = DECREASED
           fsocialspending, # FACTOR SCORE FOR SOCIAL SPENDING ITEMS (EIGELVALUE = 2.60)
           fracking, # 2 = FAVORS FRACKING, 1 = NEITHER FAVOR/OPPOSE, 0 = OPPOSES FRACKING
           gwaction, # 6 = GOV SHOULD BE DOING GREAT DEAL MORE FOR GLOBAL WARMING ... 0 = LESS
           fenviron, # FACTOR SCORE FOR ENVIRONMENTAL ITEMS (EIGENVALUE = 2.66)
           paidleave, # 6 = STRONGLY SUPPORTS PAID FAMILY LEAVE ... 0 = STRONGLY OPPOSES
           glservice, # 5 = REQUIRE SERVICE FOR GAY COUPLES ... 0 = REFUSE SERVICE
           transbath, # 5 = TRANS USE BATHROOM OF CHOICE ... 0 = USE BATHROOM OF GENDER BORN WITH
           gaydiscrim, # 3 = STRONGLY FAVOR ANTIDISCRIMINATION LAWS ... 0 = STRONGLY OPPOSE
           gayadopt, # 1 = GAYS AND LESBIANS SHOULD BE ABLE TO ADOPT CHILDREN, 0 = SHOULD NOT
           fgaylesbian, # FACTOR SCORE FOR FOUR SEXUAL ORIENTATION ITEMS (EIGENVALUE 2.24)
           fgaylesbian1, # FACTOR SCORE FOR SIX SEXUAL ORIENTATION ITEMS (EIGENVALUE = 3.43)
           abortion, # 3 = ALL CIRCUMSTANCE, 2 = MANY REASONS, 1 = RAPE, ETC., 0 = NEVER
           dpenalty, # 3 = STRONGLY SUPPORTS DEATH PENALTY ... 0 = STRONGLY OPPOSES
           freligion1, # FACTOR SCORE FOR RELIGIOSITY VARIABLES (W/O CHATTEND) (EIGENVALUE - 2.39)
           freligion, # FACTOR SCORE FOR FOUR RELIGIOSITY VARIABLES (EIGENVALUE 2.91)
           educ1, # HIGHEST LEVEL OF EDUCATION: 1 = LESS THAN 1ST GRADE ... 16 = DOCTORATE
           educ, # 1 = LESS THAN HIGH SCHOOL ... 8 = DOCTORATE OR PROFESSIONAL
           speduc1, # HIGHEST LEVEL OF EDUCATION: 1 = LESS THAN 1ST GRADE ... 16 = DOCTORATE
           speduc, # 1 = LESS THAN HIGH SCHOOL ... 8 = DOCTORATE OR PROFESSIONAL
           socialclass, # 
           race, # 1 = WHITE, 2 = BLACK, 3 = ASIAN, 4 = NATIVE, 5 = HISPANIC, 6 = OTHER
           hispanic, # 1 = R IS HISPANIC, 0 = OTHERWISE
           white, # 1 = R IS WHITE NON-HISPANIC, 0 = OTHERWISE
           white1, # 1 = R IS WHITE (INCLUDING HISPANIC WHITES), 0 = OTHERWISE
           black, # 1 = R IS BLACK NON-HISPANIC, 0 = OTHERWISE
           asian, # 1 = R IS ASIAN NON-HISPANIC, 0 = OTHERWISE
           natamer, # 1 = R IS NATIVE AMERICAN NON-HISPANIC, 0 = OTHERWISE
           otherrace, # 1 = R IS OTHER OR MIXED RACE, 0 = OTHERWISE
           grewup, # STATE, TERRITORY, OR COUNTRY IN WHICH R GREW UP
           chowlong, # LENGTH OF TIME LIVED IN COMMUNITY (YEARS)
           ahowlong, # HOW LONG AT ADDRESS: 1 = 0-1 YEARS ... 9 = 30 OR MORE YEARS
           gender, # 1 = R IS A WOMAN, 0 = MAN
           othergender, # 1 = R REPORTS BEING OTHER GENDER, 0 = OTHERWISE
           wsexist, # 4 = R AGREES THAT MANY WOMEN MISINTERPRET STATEMENTS AS SEXIST
           wfailappr, # 4 = R AGREES MOST WOMEN FAIL TO APPRECIATE WHAT MEN DO FOR THEM
           wcontrolmen, # 4 = R AGREES THAT WOMEN SEEK POWER BY GETTING CONTROL OVER MEN
           wmenleash, # R AGREES THAT SOME WOMEN TRY TO PUT MEN ON A LEASH
           fantiwomen, # FACTOR SCORE FOR THREE ANTIWOMEN ITEMS (EIGENVALUE = 2.46)
           fantiwomen1, # FACTOR SCORE FOR FOUR ANTIWOMEN ITEMS (EIGENVALUE = 2.46)
           sexorient, # 1 = HETEROSEXUAL, 2 = HOMOSEXUAL, 3 = BISEXUAL
           heterosexual, # 1 = R IS HETEROSEXUAL, 0 = OTHERWISE
           homosexual, # 1 = R IS HOMOSEXUAL, 0 = OTHERWISE
           bisexual, # 1 = R IS BISEXUAL, 0 = OTHERWISE
           knowgay, # 1 = R KNOWS SOMEONE WHO IS GAY, 0 = OTHERWISE
           know, # ADDITIVE SCALE BASED ON 9 KNOWLEDGE ITEMS (ALPHA = 0.721)
           taxmillion, # 2 = SUPPORTS INCREASING TAXES ON MILLIONAIRES, 1 = NEUTRAL, 0 = OPPOSE
           vaccines, # 6 = STRONGLY SUPPORTS VACCINES IN SCHOOLS ... 0 = STRONGLY OPPOSE
           govinequality, # 2 = R SUPPORT GOV EFFORTS TO REDUCE INEQUALITY, 1 = NEUTRAL, 0 = OPPOSE
           equalpay, # 6 = R STRONGLY SUPPORTS EQUAL PAY FOR EQUAL WORK ... 0 = STRONGLY OPPOSE
           pubsecurity, # 2 = CHANGES IN SECURITY GONE TOO FAR, 1 = ABOUT RIGHT, 0 = NOT FAR ENOUGH
           immlevel, # 4 = IMMIGRATION SHOULD BE INCREASED A LOT ... 0 = DECREASED A LOT
           immtakejobs, # 3 = VERLY LIKELY IMMIGRANTS TAKE JOBS ... 0 = NOT LIKELY AT ALL
           benriskvaccines, # 6 = BENEFITS MUCH GREATER FOR VACCINES ... 0 = RISK MUCH GREATER
           libconpost1, # 6 = EXTREMELY CONSERVATIVE ... 0 = EXTREMELY LIBERAL
           libconpost3, # FORCED CHOICE ID: 2 = CONSERVATIVE, 1 = MODERATE, 0 = LIBERAL
           govwiretaps, # 2 = GOV WIRETAPS GONE TOO FAR, 1 = ABOUT RIGHT, 0 = NOT FAR ENOUGH
           potlegal, # 2 = FAVORS POT LEGALIZATION, 1 = NEITHER FAVOR/OPPOSE, 0 = OPPOSES
           regulbanks, # 2 = SUPPORTS MORE BANK REGULATION, 1  = SAME AMOUNT, 0 = LESS REGULATION
           govprob, # 1 = GOV DOING TOO MUCH, 0 = PROBLEMS ARE BIGGER
           fmarket, # 1 = FREE MARKET CAN HANDLE PROBLEMS, 0 = GOV NEEDED TO SOLVE PROBLEMS
           govless, # 1 = LESS GOV THE BETTER, 0 = GOV SHOULD DO MORE THINGS
           fantigov, # FACTOR SCORE FOR ANTI-GOV ITEMS (EIGENVALUE = 1.93)
           gregbus, # 4 = A GREAT DEAL OF REGULATION IS GOOD FOR SOCIETY ... 0 = NONE AT ALL
           partycons, # 1 = ONE PARTY IS MORE CONSERVATIVE THAN THE OTHER, 0 = OTHERWISE
           consparty, # 1 = REP ARE MORE CONSERVATIVE, 0 = DEMS ARE MORE CONSERVATIVE
           consparty3, # 1 = REP ARE MORE CONSERVATIVE, 0.5 = NO DIFF, 0 = DEMS ARE MORE CONS
           minwage, # 2 = MIN WAGE SHOULD BE INCREASED, 1 = KEPT SAME, 0 = DECREASED OR ELIMINATED
           shealthcare7, # 6 = STRONG INCREASES IN HEALTH CARE SPENDING ... 0 = STRONG DECREASES
           madjust, # WE SHOULD ADJUST MORALITY TO CHANGING WORLD: 4 = STRONGLY AGREE
           mbreakdown, # NEWER LIFESTYLES CONTRIBUTING TO BREAKDOWN OF SOCIETY: 4 = STRONGLY AGREE
           mtolerant, # WE SHOULD BE TOLERANT OF THOSE WITH DIFFERENT MORALITY: 4 = STRONGLY AGREE
           mtraditional, # COUNTY BETTER WITH EMPHASIS ON TRADITIONAL FAMILY TIES: 4 = STRONG A
           fmoral, # FACTOR SCORE FOR FOUR MORAL TRADITIONALISM ITEMS (EIGENVALUE = 2.16)
           bspecial, # BLACKS SHOULD WORK WAY UP WITHOUT SPECIAL FAVORS: 4 = STRONGLY AGREE
           bdifficult, # SLAVERY AND DISCRIMINATION PREVENT BLACKS FROM IMPROVING: 4 = STRONG A
           bless, # OVER THE PAST FEW YEARS BLACKS HAVE GOTTEN LESS THAN THEY DESERVE: 4 = STRONG A
           btryharder, # BLACKS COULD BE BETTER OFF IF THEY TRIED HARDER: 4 = STRONG AGREE
           fblack, # FACTOR SCORE FOR BSPECIAL, BDIFFICULT, BLESS, BTRYHARDER (EIGENVALUE = 2.74)
           nocare, # PUBLIC OFFICIALS DON'T CARE WHAT PEOPLE LIKE ME THINK: 4 = STRONGLY AGREE
           nosay, # PEOPLE LIKE ME HAVE NO SAY OVER WHAT GOVERNMENT DOES: 4 = STRONGLY AGREE
           ggoodunder, # R HAS GOOD UNDERSTANDING OF ISSUES FACING COUNTRY: 4 = STRONGLY AGREE
           bjobprefer, # 3 = STRONGLY FAVOR PREFERENTIAL TREATMENT FOR BLACKS IN HIRING, 0 = OPPOSE
           authind, # 2 = RESPECT FOR ELDERS ... 0 = INDEPENDENCE
           authmanners, # 2 = PREFERS GOOD MANNERS ... 0 = CURIOSITY
           authobed, # 2 = PREFERS OBEDIENCE ... 0 = SELF-RELIANCE
           authwbehaved, # 2 = PREFERS WELL-BEHAVED ... 0 = CONSIDERATE
           fauthoritarian, # FACTOR SCORE FOR FOUR AUTHORITARIANISM ITEMS (EIGENVALUE = 1.94)
           eequalopp, # OUR SOCIETY SHOULD DO ALL POSSIBLE FOR EQUAL OPPORTUNITY: 4 = STRONGLY A
           eworry, # USA WOULD BE BETTER OFF IF WE WORRIED LESS ABOUT EQUALITY: 4 = STRONG A
           emorechance, # IT IS A BIG PROBLEM IF SOME HAVE MORE CHANCES THAN OTHERS: 4 = STRONG A
           efair, # IF PEOPLE TREATED MORE EQUAL USA WOULD HAVE FEWER PROBLEMS: 4 = STRONG A
           fequal, # FACTOR SCORE FOR FOUR EQUALITY ITEMS (EIGENVALUE = 2.06)
           polinterest, # 3 = VERY INTERESTED, 2 = INTERESTED, 1 = NOT VERY, 0 = NOT AT ALL
           polfollows, # 3 = FOLLOWS POLITICS IN MEDIA VERY CLOSELY ... 0 = NOT AT ALL
           polunderstand, # 4 = UNDERSTANDS MOST IMPORTANT ISSUES IN THE COUNTRY ... 0 = DOES NOT
           fpolengage, # FACTOR SCORE FOR THREE POLITICAL ENGAGEMENT ITEMS (EIGENVALUE = 2.13)
           rdpartyviews, # 0 = NO PARTY, 1 = DEMOCRATIC, 2 = REPUBLICAN, 3 = OTHER
           dldemparty, # LIKE-DISLIKE: DEMOCRATIC PARTY: 10 = STRONGLY LIKE
           dlrepparty, # LIKE-DISLIKE: REPUBLICAN PARTY: 10 = STRONGLY LIKE
           lrdemparty, # LEFT-RIGHT: DEMOCRATIC PARTY (10 = VERY CONSERVATIVE)
           lrrepparty, # LEFT-RIGHT: REPUBLICAN PARTY (10 = VERY CONSERVATIVE)
           lrself, # LEFT-RIGHT: SELF: VERY CONSERVATIVE
           partyclosest, # 0 = DEMOCRATS, 1 = REPUBLICANS, 2 = OTHER PARTY
           partycloser, # FOR NON-CLOSE: 0 = CLOSER TO DEMS, 1 = CLOSER TO REPS, 2 = CLOSER TO 
           libconpost, # 6 = STRONG CONSERVATIVE, 0 = STRONG LIBERAL
           policylibcon, # FACTOR SCORE FOR DOMESTIC POLICY ITEMS (EIGENVALUE = 3.09)
           partyfold, # FOLDED PARTISANSHIP: 3 = STRONG PARTISAN ... 0 = PURE INDEPENDENT
           libconfold, # FOLDED IDEOLOGY: 3 = STRONG IDEOLOGUE ... 0 = PURE MODERATE
           gaymarriage, # 1 = GAYS AND LESBIANS CAN MARRY, 0 = CIVIL UNIONS, -1 = NO LEGAL RECOG
           gmsupport, # 1 = SUPPORTS GAY MARRIAGE, 0 = OTHERWISE
           gmoppose, # 1 = OPPOSES GAY MARRIAGE, 0 = OTHERWISE
           gmneutral, # 1 = NEUTRAL TOWARD GAY MARRIAGE OR SUPPORTS CIVIL UNIONS, 0 = OTHERWISE
           ))
```

Input geographic data

```{r}
geo <- read.csv("2016_Population_Density_by_Congressional_District.csv")
```

